export const blogCategories = [
  "Technology",
  "Lifestyle",
  "Travel",
  "Food",
  "Fashion",
  "Health & Fitness",
  "Personal Development",
  "Finance",
  "Education",
  "Parenting",
  "Business",
  "Entertainment",
  "Sports",
  "Photography",
  "Music",
  "Art & Design",
  "DIY & Crafts",
  "Gaming",
  "Automotive",
  "Politics",
  "Environment",
  "Science",
  "Marketing",
  "Career Advice",
  "Real Estate",
  "Relationships",
  "Spirituality",
  "History",
  "Culture",
  "Books & Literature",
  "Movies & TV Shows",
];
